AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Stack Template

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  MyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: MyPublicSubnet

  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: MyPrivateSubnet

Outputs:
  VpcId:
    Value: !Ref MyVPC
    Description: The ID of the VPC
  PublicSubnetId:
    Value: !Ref MyPublicSubnet
    Description: The ID of the public subnet
  PrivateSubnetId:
    Value: !Ref MyPrivateSubnet
    Description: The ID of the private subnet
